services:
  - type: web
    name: tienda-ropa-frontend
    env: static
    buildCommand: npm install && npm run build-web
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
